import {useEffect,useMemo,useState} from "react";
import {BarChart3,ShieldCheck,Download,TrendingUp,Percent,IndianRupee} from "lucide-react";
import {api} from "../api"; import {money} from "../utils"; import {Card,Badge,Button,Empty} from "../components/UI";
export function Reports(){
 const [employees,setEmployees]=useState([]),[runs,setRuns]=useState([]),[payrolls,setPayrolls]=useState([]),[err,setErr]=useState("");
 useEffect(()=>{(async()=>{try{const es=await api.get("/employees"),rs=await api.get("/payroll-runs");setEmployees(es);setRuns(rs);let p=[];for(const r of rs){try{p.push(...await api.get(`/payroll-runs/${r.runId}/payrolls`))}catch{}}setPayrolls(p)}catch(e){setErr(e.message)}})()},[]);
 const byDept=useMemo(()=>{const m={};employees.forEach(e=>{const d=e.department?.departmentName||"Unassigned";m[d]=(m[d]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])},[employees]);
 const avg=payrolls.length?payrolls.reduce((s,p)=>s+Number(p.netSalary||0),0)/payrolls.length:0;
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">INSIGHTS</span><h1>Reports & analytics</h1><p className="muted">Live aggregates built from records returned by your backend API.</p></div><Button variant="ghost" icon={Download} onClick={()=>window.print()}>Print report</Button></div>{err&&<div className="error-box">{err}</div>}<div className="stat-grid"><Card><div className="stat-head"><span>PEOPLE</span><BarChart3 size={17}/></div><b className="stat-number">{employees.length}</b><div className="trend">Across all departments</div></Card><Card><div className="stat-head"><span>PAYROLL RECORDS</span><TrendingUp size={17}/></div><b className="stat-number">{payrolls.length}</b><div className="trend">Stored employee pays</div></Card><Card><div className="stat-head"><span>AVG NET PAY</span><IndianRupee size={17}/></div><b className="stat-number">{money(avg)}</b><div className="trend">From computed payroll</div></Card><Card><div className="stat-head"><span>COMPLETED RUNS</span><Percent size={17}/></div><b className="stat-number">{runs.filter(r=>r.status==="DISBURSED").length}</b><div className="trend">Disbursed payroll cycles</div></Card></div><div className="dashboard-grid"><Card><div className="section-head"><div><span className="eyebrow">WORKFORCE MIX</span><h3>Employees by department</h3></div></div>{byDept.length?<div className="horizontal-bars">{byDept.map(([d,n])=><div key={d}><div><span>{d}</span><b>{n}</b></div><div className="hbar"><i style={{width:`${Math.max(8,n/Math.max(...byDept.map(x=>x[1]))*100)}%`}}/></div></div>)}</div>:<Empty/>}</Card><Card><div className="section-head"><div><span className="eyebrow">PAYROLL HISTORY</span><h3>Run ledger</h3></div></div>{runs.length?<div className="detail-list">{runs.slice().sort((a,b)=>b.runId-a.runId).map(r=><div key={r.runId}><span>Run #{r.runId} · {r.month}/{r.year}</span><b>{money(r.totalNet)} <Badge>{r.status}</Badge></b></div>)}</div>:<Empty/>}</Card></div></div>
}

export function Compliance(){
 const [employees,setEmployees]=useState([]),[payrolls,setPayrolls]=useState([]),[err,setErr]=useState("");
 useEffect(()=>{(async()=>{try{const es=await api.get("/employees"),rs=await api.get("/payroll-runs");setEmployees(es);let p=[];for(const r of rs){try{p.push(...await api.get(`/payroll-runs/${r.runId}/payrolls`))}catch{}}setPayrolls(p)}catch(e){setErr(e.message)}})()},[]);
 const checks=[
  ["PAN coverage",employees.filter(e=>e.pan).length,employees.length,"Employees with PAN recorded"],
  ["UAN coverage",employees.filter(e=>e.uan).length,employees.length,"Employees with UAN recorded"],
  ["ESIC coverage",employees.filter(e=>e.esicNo).length,employees.length,"Employees with ESIC number"],
  ["PF processed",payrolls.filter(p=>Number(p.pfEmployee||0)>0).length,payrolls.length,"Computed payroll rows with employee PF"],
  ["ESI processed",payrolls.filter(p=>Number(p.esiEmployee||0)>0).length,payrolls.length,"Computed rows where ESI applies"],
 ];
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">CONTROL & GOVERNANCE</span><h1>Compliance</h1><p className="muted">Operational checks based on the employee and payroll data your API currently exposes.</p></div><div className="notice"><ShieldCheck size={16}/> Review before statutory filing</div></div>{err&&<div className="error-box">{err}</div>}<div className="compliance-grid">{checks.map(([name,a,b,desc])=>{const pct=b?Math.round(a/b*100):0;return <Card key={name}><div className="compliance-top"><div className="compliance-icon"><ShieldCheck size={18}/></div><Badge>{pct===100?"READY":pct>0?"REVIEW":"MISSING"}</Badge></div><h3>{name}</h3><p className="muted">{desc}</p><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="compliance-score"><b>{a}</b><span>of {b} · {pct}%</span></div></Card>})}</div></div>
}
