import { useEffect,useMemo,useState } from "react";
import { Plus,Pencil,Trash2,MapPin,Users } from "lucide-react";
import {api} from "../api"; import {Button,Card,Field,Input,Modal,Toolbar,Empty,Confirm} from "../components/UI";
export default function Departments(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({departmentName:"",location:"",managerName:""}),[confirm,setConfirm]=useState(null),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 const load=async()=>{try{setItems(await api.get("/departments"))}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.departmentName} ${x.location} ${x.managerName}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const save=async e=>{e.preventDefault();setLoading(true);try{if(editing)await api.put(`/departments/${editing}`,form);else await api.post("/departments",form);setOpen(false);setEditing(null);load()}catch(x){setErr(x.message)}finally{setLoading(false)}};
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">ORGANIZATION</span><h1>Departments</h1><p className="muted">Keep your organizational structure synchronized with the backend.</p></div><Button icon={Plus} onClick={()=>{setEditing(null);setForm({departmentName:"",location:"",managerName:""});setOpen(true)}}>Add department</Button></div>{err&&<div className="error-box">{err}</div>}<Card><div className="table-toolbar"><Toolbar value={q} onChange={setQ}/><span className="count">{filtered.length} departments</span></div>{filtered.length?<div className="dept-grid">{filtered.map(d=><div className="dept-card" key={d.departmentId}><div className="dept-icon"><Users size={20}/></div><div className="dept-main"><span className="eyebrow">DEPT #{d.departmentId}</span><h3>{d.departmentName}</h3><p><MapPin size={14}/>{d.location||"Location not set"}</p><small>Manager · {d.managerName||"Not assigned"}</small></div><div className="row-actions"><button className="icon-btn" onClick={()=>{setEditing(d.departmentId);setForm({departmentName:d.departmentName||"",location:d.location||"",managerName:d.managerName||""});setOpen(true)}}><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>setConfirm(d)}><Trash2 size={15}/></button></div></div>)}</div>:<Empty/>}</Card>
 {open&&<Modal title={editing?"Edit department":"Add department"} onClose={()=>setOpen(false)}><form onSubmit={save}><Field label="Department name"><Input required value={form.departmentName} onChange={e=>setForm({...form,departmentName:e.target.value})}/></Field><Field label="Location"><Input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field label="Manager name"><Input value={form.managerName} onChange={e=>setForm({...form,managerName:e.target.value})}/></Field><div className="modal-actions"><Button variant="ghost" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading}>Save department</Button></div></form></Modal>}
 {confirm&&<Confirm title="Delete department?" text="The backend will reject this if employees still reference it." onNo={()=>setConfirm(null)} onYes={async()=>{try{await api.del(`/departments/${confirm.departmentId}`);setConfirm(null);load()}catch(e){setErr(e.message);setConfirm(null)}}}/>}</div>
}
