import { useEffect, useMemo, useState } from "react";
import { Plus, Pencil, UserX, Mail, Phone, UserRound, Download } from "lucide-react";
import { api } from "../api";
import { money, today } from "../utils";
import { Button, Card, Field, Input, Select, Modal, Toolbar, Badge, Empty, Confirm } from "../components/UI";

const empty={employeeName:"",designation:"",email:"",phone:"",joiningDate:today(),basicSalary:"",departmentId:"",pan:"",uan:"",esicNo:""};

export default function Employees(){
 const [items,setItems]=useState([]),[depts,setDepts]=useState([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[err,setErr]=useState(""),[loading,setLoading]=useState(false),[confirm,setConfirm]=useState(null);
 const load=async()=>{try{setItems(await api.get("/employees"));setDepts(await api.get("/departments"))}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(e=>`${e.employeeName} ${e.email} ${e.designation}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const save=async e=>{e.preventDefault();setLoading(true);setErr("");const body={...form,basicSalary:form.basicSalary?Number(form.basicSalary):null,departmentId:form.departmentId?Number(form.departmentId):null};try{if(editing) await api.put(`/employees/${editing}`,body);else await api.post("/employees",body);setOpen(false);setEditing(null);setForm(empty);await load()}catch(x){setErr(x.message)}finally{setLoading(false)}};
 const edit=e=>{setEditing(e.employeeId);setForm({employeeName:e.employeeName||"",designation:e.designation||"",email:e.email||"",phone:e.phone||"",joiningDate:e.joiningDate||today(),basicSalary:e.basicSalary||"",departmentId:e.department?.departmentId||"",pan:e.pan||"",uan:e.uan||"",esicNo:e.esicNo||""});setOpen(true)};
 const deactivate=async id=>{try{await api.del(`/employees/${id}`);setConfirm(null);load()}catch(e){setErr(e.message)}};
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">PEOPLE DIRECTORY</span><h1>Employees</h1><p className="muted">Create, update and deactivate employee records directly in PostgreSQL.</p></div><Button icon={Plus} onClick={()=>{setEditing(null);setForm(empty);setOpen(true)}}>Add employee</Button></div>
 {err&&<div className="error-box">{err}</div>}<Card><div className="table-toolbar"><Toolbar value={q} onChange={setQ} placeholder="Search name, email or designation"/><span className="count">{filtered.length} people</span></div>
 {filtered.length?<div className="data-table"><div className="tr th"><span>Employee</span><span>Department</span><span>Contact</span><span>Basic salary</span><span>Status</span><span/></div>{filtered.map(e=><div className="tr" key={e.employeeId}><div className="person"><div className="avatar">{e.employeeName?.slice(0,1)}</div><div><b>{e.employeeName}</b><small>#{e.employeeId} · {e.designation||"—"}</small></div></div><span>{e.department?.departmentName||"—"}</span><div className="contact-stack"><span><Mail size={13}/>{e.email}</span><span><Phone size={13}/>{e.phone||"—"}</span></div><b>{money(e.basicSalary)}</b><Badge>{e.status}</Badge><div className="row-actions"><button className="icon-btn" onClick={()=>edit(e)} title="Edit"><Pencil size={15}/></button>{e.status==="ACTIVE"&&<button className="icon-btn danger-icon" onClick={()=>setConfirm(e)} title="Deactivate"><UserX size={15}/></button>}</div></div>)}</div>:<Empty title="No matching employees" text="Try another search or add your first employee."/>}</Card>
 {open&&<Modal title={editing?"Edit employee":"Add employee"} onClose={()=>setOpen(false)} wide><form onSubmit={save}><div className="form-grid"><Field label="Full name"><Input required value={form.employeeName} onChange={e=>setForm({...form,employeeName:e.target.value})}/></Field><Field label="Designation"><Input value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></Field><Field label="Email"><Input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Joining date"><Input type="date" value={form.joiningDate} onChange={e=>setForm({...form,joiningDate:e.target.value})}/></Field><Field label="Basic salary"><Input type="number" min="0" value={form.basicSalary} onChange={e=>setForm({...form,basicSalary:e.target.value})}/></Field><Field label="Department"><Select required value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Select department</option>{depts.map(d=><option value={d.departmentId} key={d.departmentId}>{d.departmentName}</option>)}</Select></Field><Field label="PAN"><Input value={form.pan} onChange={e=>setForm({...form,pan:e.target.value})}/></Field><Field label="UAN"><Input value={form.uan} onChange={e=>setForm({...form,uan:e.target.value})}/></Field><Field label="ESIC number"><Input value={form.esicNo} onChange={e=>setForm({...form,esicNo:e.target.value})}/></Field></div><div className="modal-actions"><Button variant="ghost" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading} type="submit">Save employee</Button></div></form></Modal>}
 {confirm&&<Confirm title="Deactivate employee?" text={`${confirm.employeeName} will be marked TERMINATED in the backend.`} onNo={()=>setConfirm(null)} onYes={()=>deactivate(confirm.employeeId)}/>}</div>
}
