import {useEffect,useState} from "react";
import {Plus,Check, X,CalendarDays} from "lucide-react";
import {api} from "../api"; import {today} from "../utils"; import {useAuth} from "../auth"; import {Button,Card,Field,Input,Select,Modal,Badge,Empty} from "../components/UI";
export default function Leaves(){
 const {user}=useAuth(); const [items,setItems]=useState([]),[employees,setEmployees]=useState([]),[form,setForm]=useState({employeeId:"",leaveType:"CASUAL",startDate:today(),endDate:today(),reason:""}),[open,setOpen]=useState(false),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 const load=async()=>{try{setEmployees(await api.get("/employees"));const es=await api.get("/employees");let all=[];for(const e of es){try{const x=await api.get(`/leaves/employee/${e.employeeId}`);all.push(...x)}catch{}}setItems(all)}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setLoading(true);try{await api.post("/leaves",{employee:{employeeId:Number(form.employeeId)},leaveType:form.leaveType,startDate:form.startDate,endDate:form.endDate,reason:form.reason,approvalStatus:"PENDING"});setOpen(false);load()}catch(x){setErr(x.message)}finally{setLoading(false)}};
 const decide=async(id,ok)=>{try{const approver=user?.userId||1;await api.put(`/leaves/${id}/${ok?"approve":"reject"}?${ok?"approvedBy":"rejectedBy"}=${approver}`);load()}catch(e){setErr(e.message)}};
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">TIME OFF</span><h1>Leave desk</h1><p className="muted">Apply leave and approve/reject requests with live backend state.</p></div><Button icon={Plus} onClick={()=>setOpen(true)}>Apply leave</Button></div>{err&&<div className="error-box">{err}</div>}<Card><div className="section-head"><div><span className="eyebrow">REQUESTS</span><h3>{items.length} leave records</h3></div><CalendarDays size={19}/></div>{items.length?<div className="data-table"><div className="tr th"><span>Employee</span><span>Type</span><span>Dates</span><span>Reason</span><span>Status</span><span>Action</span></div>{items.map(x=><div className="tr" key={x.leaveId}><span><b>{x.employee?.employeeName||`#${x.employee?.employeeId}`}</b></span><span>{x.leaveType}</span><span>{x.startDate} → {x.endDate}</span><span>{x.reason||"—"}</span><Badge>{x.approvalStatus}</Badge><div className="row-actions">{x.approvalStatus==="PENDING"&&<><button className="icon-btn success-icon" onClick={()=>decide(x.leaveId,true)}><Check size={15}/></button><button className="icon-btn danger-icon" onClick={()=>decide(x.leaveId,false)}><X size={15}/></button></>}</div></div>)}</div>:<Empty title="No leave records" text="Apply the first request and it will be stored in leave_record."/>}</Card>
 {open&&<Modal title="Apply leave" onClose={()=>setOpen(false)}><form onSubmit={save}><Field label="Employee"><Select required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option value={e.employeeId} key={e.employeeId}>{e.employeeName}</option>)}</Select></Field><Field label="Leave type"><Select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}>{["CASUAL","SICK","EARNED","UNPAID","MATERNITY","OTHER"].map(x=><option key={x}>{x}</option>)}</Select></Field><div className="two"><Field label="Start date"><Input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field label="End date"><Input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field></div><Field label="Reason"><textarea className="input textarea" rows="4" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field><div className="modal-actions"><Button variant="ghost" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading}>Submit request</Button></div></form></Modal>}</div>
}
