import {useEffect,useState} from "react";
import {Play,Calculator,CheckCircle2,Send,Eye,FileText} from "lucide-react";
import {api} from "../api"; import {money,monthName,can} from "../utils"; import {useAuth} from "../auth"; import {Button,Card,Field,Input,Modal,Badge,Empty} from "../components/UI";
export default function Payroll(){
 const {user}=useAuth();

 const canManagePayroll =
     can(user?.role, ["PAYROLL_ADMIN", "SYSTEM_ADMIN"]);

 const canApprovePayroll =
     can(user?.role, ["FINANCE_MANAGER", "SYSTEM_ADMIN"]);const [runs,setRuns]=useState([]),[selected,setSelected]=useState(null),[rows,setRows]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({month:new Date().getMonth()+1,year:new Date().getFullYear()}),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 const load=async()=>{try{setRuns(await api.get("/payroll-runs"))}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);
 const action=async(fn)=>{setLoading(true);try{await fn();await load();}catch(e){setErr(e.message)}finally{setLoading(false)}};
 const initiate=async e=>{e.preventDefault();const me=await api.get("/employees/active");await action(()=>api.post(`/payroll-runs/initiate?month=${form.month}&year=${form.year}&initiatedBy=${user?.userId||1}`));setOpen(false)};
 const view=async r=>{setSelected(r);try{setRows(await api.get(`/payroll-runs/${r.runId}/payrolls`))}catch(e){setErr(e.message)}};
 const compute=r=>action(()=>api.post(`/payroll-runs/${r.runId}/compute`));
 const approve=r=>action(()=>api.post(`/payroll-runs/${r.runId}/approve?approvedBy=${user?.userId||1}`));
 const disburse=r=>action(()=>api.post(`/payroll-runs/${r.runId}/disburse`));
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">PAY CYCLE</span><h1>Payroll runs</h1><p className="muted">Initiate → compute → approve → disburse. Calculations stay on the backend.</p></div>{canManagePayroll && (<Button icon={Play} onClick={()=>setOpen(true)}>Initiate run</Button>)}</div>{err&&<div className="error-box">{err}</div>}<div className="run-grid">{runs.slice().sort((a,b)=>b.runId-a.runId).map(r=><Card className="run-card" key={r.runId}><div className="run-top"><div className="run-icon"><Calculator size={19}/></div><Badge>{r.status}</Badge></div><span className="eyebrow">RUN #{r.runId}</span><h3>{monthName(r.month)} {r.year}</h3><div className="run-numbers"><div><small>Gross</small><b>{money(r.totalGross)}</b></div><div><small>Net</small><b>{money(r.totalNet)}</b></div><div><small>People</small><b>{r.employeeCount||0}</b></div></div><div className="run-actions"><Button variant="ghost" icon={Eye} onClick={()=>view(r)}>View</Button>{r.status==="DRAFT" && canManagePayroll && (<Button icon={Calculator} loading={loading} onClick={()=>compute(r)}>Compute</Button>)}{r.status==="COMPUTED"&& canApprovePayroll && (<Button icon={CheckCircle2} loading={loading} onClick={()=>approve(r)}>Approve</Button>)}{r.status==="APPROVED"&& canApprovePayroll && (<Button icon={Send} loading={loading} onClick={()=>disburse(r)}>Disburse</Button>)}</div></Card>)}{!runs.length&&<Card><Empty title="No payroll runs" text="Initiate a run to let the backend calculate payroll for all active employees."/></Card>}</div>
 {selected&&<Modal title={`${monthName(selected.month)} ${selected.year} · Payroll details`} wide onClose={()=>setSelected(null)}><div className="data-table"><div className="tr th"><span>Employee</span><span>Gross</span><span>Deductions</span><span>Net</span><span>Payment</span><span/></div>{rows.map(x=><div className="tr" key={x.payrollId}><span><b>{x.employee?.employeeName||`#${x.employee?.employeeId}`}</b><small>{x.payrollMonth}</small></span><b>{money(x.grossSalary)}</b><span>{money(x.totalDeductions)}</span><b>{money(x.netSalary)}</b><Badge>{x.paymentStatus}</Badge><span/></div>)}</div></Modal>}
 {selected&&<Modal title={`${monthName(selected.month)} ${selected.year} · Payroll details`} wide onClose={()=>setSelected(null)}><div className="data-table"><div className="tr th"><span>Employee</span><span>Gross</span><span>Deductions</span><span>Net</span><span>Payment</span><span/></div>{rows.map(x=><div className="tr" key={x.payrollId}><span><b>{x.employee?.employeeName||`#${x.employee?.employeeId}`}</b><small>{x.payrollMonth}</small></span><b>{money(x.grossSalary)}</b><span>{money(x.totalDeductions)}</span><b>{money(x.netSalary)}</b><Badge>{x.paymentStatus}</Badge><span/></div>)}</div></Modal>}
 {open&&<Modal title="Initiate payroll run" onClose={()=>setOpen(false)}><form onSubmit={initiate}><Field label="Month"><Input type="number" min="1" max="12" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></Field><Field label="Year"><Input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></Field><div className="notice"><Calculator size={16}/><span>The backend will create a DRAFT run. Compute uses active employees, salary structures, attendance, allowances and deductions.</span></div><div className="modal-actions"><Button variant="ghost" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading}>Create draft</Button></div></form></Modal>}</div>
}
