import {useEffect,useState} from "react";
import {FileText,Mail,Layers3,RefreshCw} from "lucide-react";
import {api} from "../api"; import {money} from "../utils"; import {Button,Card,Field,Input,Modal,Badge,Empty} from "../components/UI";
export default function Payslips(){
 const [employees,setEmployees]=useState([]),[payrolls,setPayrolls]=useState([]),[selected,setSelected]=useState(null),[err,setErr]=useState(""),[loading,setLoading]=useState(false),[payrollId,setPayrollId]=useState("");
 const load=async()=>{try{const es=await api.get("/employees");setEmployees(es);let all=[];for(const e of es){try{const p=await api.get(`/payroll-runs/employee/${e.employeeId}`);all.push(...p)}catch{}}setPayrolls(all)}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);
 const generate=async id=>{setLoading(true);try{await api.post(`/payslips/generate/${id}`);await load()}catch(e){setErr(e.message)}finally{setLoading(false)}};
 const bulk=async()=>{setLoading(true);try{const runs=await api.get("/payroll-runs");const r=runs.slice().sort((a,b)=>b.runId-a.runId)[0];if(!r)throw Error("No payroll run exists");await api.post(`/payslips/generate-bulk/${r.runId}`);await load()}catch(e){setErr(e.message)}finally{setLoading(false)}};
 const email=async id=>{try{await api.put(`/payslips/${id}/email`);await load()}catch(e){setErr(e.message)}};
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">DOCUMENT CENTER</span><h1>Payslips</h1><p className="muted">Generate payslips from payroll records and mark them as emailed.</p></div><Button icon={Layers3} loading={loading} onClick={bulk}>Generate latest bulk</Button></div>{err&&<div className="error-box">{err}</div>}<Card><div className="filter-row"><Field label="Payroll ID"><Input type="number" value={payrollId} onChange={e=>setPayrollId(e.target.value)} placeholder="Optional"/></Field><Button variant="ghost" icon={RefreshCw} onClick={()=>payrollId?generate(payrollId):load()}>Refresh / generate</Button></div></Card><Card>{payrolls.length?<div className="data-table"><div className="tr th"><span>Employee</span><span>Month</span><span>Net salary</span><span>Payslip</span><span>Email</span><span>Action</span></div>{payrolls.map(p=><div className="tr" key={p.payrollId}><span><b>{p.employee?.employeeName||`#${p.employee?.employeeId}`}</b></span><span>{p.payrollMonth}</span><b>{money(p.netSalary)}</b><span>{p.payslip?<Badge>GENERATED</Badge>:<Badge>PENDING</Badge>}</span><span>{p.payslip?.isEmailed?<Badge>EMAILED</Badge>:<span className="muted">Not sent</span>}</span><div className="row-actions">{p.payslip?<button className="icon-btn" onClick={()=>email(p.payslip.payslipId)} title="Mark emailed"><Mail size={15}/></button>:<button className="icon-btn" onClick={()=>generate(p.payrollId)} title="Generate"><FileText size={15}/></button>}</div></div>)}</div>:<Empty title="No payroll payslips yet" text="Compute a payroll run first, then generate payslips."/ >}</Card></div>
}
