import {useEffect,useMemo,useState} from "react";
import {Plus,Pencil,Trash2,WalletCards,SlidersHorizontal} from "lucide-react";
import {api} from "../api"; import {money,today} from "../utils"; import {Button,Card,Field,Input,Select,Modal,Toolbar,Badge,Empty,Confirm} from "../components/UI";
const blank={employeeId:"",basic:"",hraPct:"40",da:"0",specialAllowance:"0",ltaAnnual:"0",medicalAllowance:"0",grossCtc:"",effectiveFrom:today(),isActive:true};
export default function Salary(){
 const [items,setItems]=useState([]),[employees,setEmployees]=useState([]),[q,setQ]=useState(""),[tab,setTab]=useState("salary"),[open,setOpen]=useState(false),[kind,setKind]=useState("salary"),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[err,setErr]=useState(""),[confirm,setConfirm]=useState(null),[loading,setLoading]=useState(false);
 const load=async()=>{try{const [s,a,d,e]=await Promise.all([api.get("/salary-structures"),api.get("/allowances"),api.get("/deductions"),api.get("/employees")]);setEmployees(e);setItems(tab==="salary"?s:tab==="allowance"?a:d)}catch(x){setErr(x.message)}};useEffect(()=>{load()},[tab]);
 const openNew=k=>{setKind(k);setEditing(null);setForm(k==="salary"?blank:{employeeId:"",allowanceType:"",deductionType:"",amount:"",effectiveFrom:today(),isActive:true});setOpen(true)};
 const save=async e=>{e.preventDefault();setLoading(true);try{let body={employee:{employeeId:Number(form.employeeId)},effectiveFrom:form.effectiveFrom,isActive:true};let path=kind==="salary"?"/salary-structures":kind==="allowance"?"/allowances":"/deductions";if(kind==="salary")body={...body,basic:Number(form.basic),hraPct:Number(form.hraPct),da:Number(form.da||0),specialAllowance:Number(form.specialAllowance||0),ltaAnnual:Number(form.ltaAnnual||0),medicalAllowance:Number(form.medicalAllowance||0),grossCtc:Number(form.grossCtc||0)};else body={...body,[kind==="allowance"?"allowanceType":"deductionType"]:kind==="allowance"?form.allowanceType:form.deductionType,amount:Number(form.amount)};if(editing)await api.put(`${path}/${editing}`,body);else await api.post(path,body);setOpen(false);load()}catch(x){setErr(x.message)}finally{setLoading(false)}};
 const filtered=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[items,q]);
 const remove=async id=>{try{const path=tab==="salary"?"/salary-structures":tab==="allowance"?"/allowances":"/deductions";await api.del(`${path}/${id}`);setConfirm(null);load()}catch(e){setErr(e.message)}};
 return <div className="fade-in"><div className="page-head"><div><span className="eyebrow">COMPENSATION</span><h1>Salary structure</h1><p className="muted">Manage core pay, recurring allowances and deductions through dedicated API endpoints.</p></div><Button icon={Plus} onClick={()=>openNew(tab==="salary"?"salary":tab)}>Add {tab==="salary"?"structure":tab}</Button></div>{err&&<div className="error-box">{err}</div>}<div className="segmented"><button className={tab==="salary"?"active":""} onClick={()=>setTab("salary")}>Salary structures</button><button className={tab==="allowance"?"active":""} onClick={()=>setTab("allowance")}>Allowances</button><button className={tab==="deduction"?"active":""} onClick={()=>setTab("deduction")}>Deductions</button></div>
 <Card><div className="table-toolbar"><Toolbar value={q} onChange={setQ} placeholder="Search employee or component"/><span className="count">{filtered.length} records</span></div>{filtered.length?<div className="data-table">{tab==="salary"?<><div className="tr th"><span>Employee</span><span>Basic</span><span>HRA</span><span>Other pay</span><span>Gross CTC</span><span/></div>{filtered.map(s=><div className="tr" key={s.structureId}><div className="person"><div className="avatar"><WalletCards size={15}/></div><div><b>{s.employee?.employeeName||`Employee #${s.employee?.employeeId}`}</b><small>#{s.structureId} · Effective {s.effectiveFrom}</small></div></div><b>{money(s.basic)}</b><span>{s.hraPct}%</span><span>{money(Number(s.da||0)+Number(s.specialAllowance||0)+Number(s.medicalAllowance||0))}</span><b>{money(s.grossCtc)}</b><div className="row-actions"><button className="icon-btn" onClick={()=>{setKind("salary");setEditing(s.structureId);setForm({employeeId:s.employee?.employeeId||"",basic:s.basic||"",hraPct:s.hraPct||40,da:s.da||0,specialAllowance:s.specialAllowance||0,ltaAnnual:s.ltaAnnual||0,medicalAllowance:s.medicalAllowance||0,grossCtc:s.grossCtc||0,effectiveFrom:s.effectiveFrom||today(),isActive:s.isActive!==false});setOpen(true)}}><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>setConfirm({id:s.structureId})}><Trash2 size={15}/></button></div></div>)}</>:<><div className="tr th"><span>Employee</span><span>Component</span><span>Amount</span><span>Effective</span><span>Active</span><span/></div>{filtered.map(x=><div className="tr" key={x.allowanceId||x.deductionId}><div className="person"><div className="avatar"><SlidersHorizontal size={15}/></div><div><b>{x.employee?.employeeName||`Employee #${x.employee?.employeeId}`}</b></div></div><span>{x.allowanceType||x.deductionType}</span><b>{money(x.amount)}</b><span>{x.effectiveFrom||"—"}</span><Badge>{x.isActive?"ACTIVE":"INACTIVE"}</Badge><div className="row-actions"><button className="icon-btn" onClick={()=>{setKind(tab);setEditing(x.allowanceId||x.deductionId);setForm({employeeId:x.employee?.employeeId||"",allowanceType:x.allowanceType||"",deductionType:x.deductionType||"",amount:x.amount||"",effectiveFrom:x.effectiveFrom||today(),isActive:x.isActive!==false});setOpen(true)}}><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>setConfirm({id:x.allowanceId||x.deductionId})}><Trash2 size={15}/></button></div></div>)}</>}</div>:<Empty title="No compensation records" text="Add a salary structure, allowance or deduction."/ >}</Card>
 {open&&<Modal title={editing?"Edit compensation":"Add compensation"} onClose={()=>setOpen(false)} wide><form onSubmit={save}><div className="form-grid"><Field label="Employee"><Select required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option key={e.employeeId} value={e.employeeId}>{e.employeeName} · #{e.employeeId}</option>)}</Select></Field>{kind==="salary"?<><Field label="Basic"><Input required type="number" value={form.basic} onChange={e=>setForm({...form,basic:e.target.value})}/></Field><Field label="HRA %"><Input type="number" value={form.hraPct} onChange={e=>setForm({...form,hraPct:e.target.value})}/></Field><Field label="DA"><Input type="number" value={form.da} onChange={e=>setForm({...form,da:e.target.value})}/></Field><Field label="Special allowance"><Input type="number" value={form.specialAllowance} onChange={e=>setForm({...form,specialAllowance:e.target.value})}/></Field><Field label="LTA annual"><Input type="number" value={form.ltaAnnual} onChange={e=>setForm({...form,ltaAnnual:e.target.value})}/></Field><Field label="Medical allowance"><Input type="number" value={form.medicalAllowance} onChange={e=>setForm({...form,medicalAllowance:e.target.value})}/></Field><Field label="Gross CTC"><Input type="number" value={form.grossCtc} onChange={e=>setForm({...form,grossCtc:e.target.value})}/></Field></>:<><Field label={kind==="allowance"?"Allowance type":"Deduction type"}><Input required value={kind==="allowance"?form.allowanceType:form.deductionType} onChange={e=>setForm({...form,[kind==="allowance"?"allowanceType":"deductionType"]:e.target.value})}/></Field><Field label="Amount"><Input required type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field></>}<Field label="Effective from"><Input type="date" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})}/></Field></div><div className="modal-actions"><Button variant="ghost" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading}>Save to backend</Button></div></form></Modal>}
 {confirm&&<Confirm title="Delete compensation record?" text="This will issue a DELETE request to the backend." onNo={()=>setConfirm(null)} onYes={()=>remove(confirm.id)}/>}</div>
}
