spring.application.name=payroll

spring.datasource.url=jdbc:postgresql://localhost:5433/payroll_db
spring.datasource.username=postgres
spring.datasource.password=Ananthi@2007

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

jwt.secret=dGhpcy1pcy1hLXZlcnktbG9uZy1hbmQtc2VjdXJlLXNlY3JldC1rZXktZm9yLWhzNTEyLWFsZ29yaXRobS0yMDI0
jwt.expiration=3600000